export const allForms = [
  {
    id: 1,
    name: "Deprem.io Enkaz Yardim",
    description: "Arama Kurtarma Talep Sistemi",
    url: "https://deprem.io/",
    category: "Enkaz Yardimlari",
  },
  {
    id: 2,
    name: "Enkaz Yardim",
    description: "Arama Kurtarma Talep Sistemi",
    url: "http://deprem.basarsoft.com.tr/",
    category: "Enkaz Yardimlari",
  },
  {
    id: 3,
    name: "Form 3",
    description: "Form 3 TEST Description",
    url: "https://www.google.com",
    category: "Gida Yardimlari",
  },
  {
    id: 4,
    name: "Form 4",
    description: "Form 4 TEST Description",
    url: "https://www.google.com",
    category: "Gida Yardimlari",
  },
  {
    id: 5,
    name: "Kahramanmaras Vinc Operatorleri",
    description: "Test formu",
    url: "https://www.google.com",
    category: "Is Makinesi Yardimlari",
  },
  {
    id: 6,
    name: "Malatya Depremzede Tasima",
    description: "Malatya merkezden araba ile depremzede tasima",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSexJOmaK-r6khyCTE9rVTr9W8QFo7aMbx4tweZEbeASJ8RRVg/viewform",
    category: "Enkaz Yardimlari",
  },
  {
    id: 7,
    name: "Kalacak Yerler Listesi",
    description:
      "Yerimiz Musait: Depremzedeler icin ucretsiz barinma saglayanlar",
    url: "https://www.google.com/maps/@37.9637812,37.5643972,9z/data=!3m1!4b1!4m2!11m1!2s8l0kZBZNRV-s0FRQwYFgHg",
    category: "Barinma Yardimlari",
  },
  {
    id: 8,
    name: "Kalacak Oteller Listesi",
    description: "Kapilarini depremzedelere acan oteller",
    url: "https://www.otelz.com/gecmisolsunturkiyem",
    category: "Barinma Yardimlari",
  },
  {
    id: 9,
    name: "Form 6",
    description: "Form 6 Description",
    url: "https://www.google.com",
    category: "Barinma Yardimlari",
  },
  {
    id: 10,
    name: "Form 6",
    description: "Form 6 Description",
    url: "https://www.google.com",
    category: "Yiyecek Yardimlari",
  },
  {
    id: 11,
    name: "Form 6",
    description: "Form 6 Description",
    url: "https://www.google.com",
    category: "Tasinma Yardimlari",
  },
];
